max_name_length: 100

user:
  valid_email_regex: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  email:
    email_length_range: 20..255
  name_validates:
    name_max_length: 50
    name_min_length: 6
  password_validates:
    password_min_length: 6
  image:
    image_path: ["image/jpeg", "image/gif", "image/png"]
    image_accept: "image/jpeg,image/gif,image/png"
  address_min_length: 2
  address_max_length: 250
  min_phone: 8
  max_phone: 11
image:
  default_avatar: "default-avatar.png"
max_name_book_length: 100
min_book_price_length: 0
max_book_price_length: 1000000
max_description_length: 60000
image_format: ["image/jpeg", "image/gif", "image/png"]
image_size: 5

min_page: 0
min_quantity: 0
image_book_admin: [200, 250]
carts:
  min_quantily: 0
