max_name_length: 100

user:
  valid_email_regex: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  email:
    email_length_range: 20..255
  name_validates:
    name_max_length: 20
  password_validates:
    password_min_length: 6
